### PR TITLE
kernel specialization

### PR DESCRIPTION
**Pull request by MuhammadAbuBakar95**

### CODE REVIEW

**Comment by caballa** [comment]
Thank you for the fixes!

**Comment by caballa** [comment]
Correct me if I'm wrong but it seems that the changes from 4 days ago are completely independent from the changes on Sep 27th.  So please, move the vagrant stuff to a different PR and we will approve it .

**Comment by MuhammadAbuBakar95** [comment]
Sorry .. I had not got your message .. Sure I will do that.

**Comment by caballa** [comment]
Can you also make a PR for the first one?

**Comment by ianamason** [comment]
The one I merged?

**Comment by caballa** [comment]
No, the one from Sep 27th

**Comment by MuhammadAbuBakar95** [comment]
I have made a separate PR for the first (27 Sep).

**Comment by caballa** [comment]
The two PR have been already merged. I close this one.

**Pull request closed without merging**
